from __future__ import annotations

import json
import logging
import time
from typing import Any

from app.agents.scenario_common import PreviewScenario, deduplicate_scenarios, filter_new_scenarios, invoke_json_scenarios, limit_scenarios
from app.core.config import get_settings

logger = logging.getLogger(__name__)

DEDUP_PROMPT = """You are Agent 3 in a QA scenario-generation graph.
Your task is to deduplicate high-level testing scenarios generated by earlier agents.

Deduplication rules:
- Remove scenarios that are semantically identical or highly similar in tester intent.
- Treat scenarios as duplicates when a tester would execute the same UI journey, validate the same business outcome, or cover the same permission/error/lifecycle behavior.
- Keep one canonical version per duplicate cluster.
- Prefer the clearer and more complete wording. If quality is similar, prefer 'agent_1' over 'agent_2'.
- Do not invent new scenarios, new domain concepts, new workflows, or new details.
- Do not significantly rewrite titles or descriptions beyond preserving one canonical existing version.
- Do not remove distinct scenarios just because they belong to the same module; only merge when the actual tester intent overlaps.

Return ONLY the deduplicated JSON array with the same shape:
[{{ 'title': string, 'description': string, 'source': string }}].
No preamble, no explanation, no markdown backticks.

Scenarios:
{scenario_json}
"""


def _scenario_json_batches(scenarios: list[PreviewScenario], max_chars: int) -> list[list[PreviewScenario]]:
    batches: list[list[PreviewScenario]] = []
    current: list[PreviewScenario] = []

    for scenario in scenarios:
        candidate = [*current, scenario]
        if current and len(json.dumps(candidate)) > max_chars:
            batches.append(current)
            current = [scenario]
        else:
            current = candidate

    if current:
        batches.append(current)

    return batches


def _llm_dedup_batch(scenarios: list[PreviewScenario], agent_name: str) -> list[PreviewScenario]:
    return invoke_json_scenarios(
        DEDUP_PROMPT.format(scenario_json=json.dumps(scenarios)),
        agent_name=agent_name,
        source=None,
    )


def _smart_dedup(
    scenarios: list[PreviewScenario],
    max_scenarios: int | None,
    existing_scenarios: list[PreviewScenario],
) -> list[PreviewScenario]:
    settings = get_settings()
    locally_clean = filter_new_scenarios(deduplicate_scenarios(scenarios), existing_scenarios)
    if not locally_clean:
        return []

    batches = _scenario_json_batches(locally_clean, settings.scenario_dedup_max_chars)
    llm_clean: list[PreviewScenario] = []

    for index, batch in enumerate(batches, start=1):
        try:
            llm_clean.extend(_llm_dedup_batch(batch, f"agent_3_batch_{index}"))
        except Exception as error:
            logger.warning("agent_3 LLM dedup batch %s/%s failed; using local batch result: %s", index, len(batches), error)
            llm_clean.extend(batch)

        if index < len(batches) and settings.scenario_agent_batch_delay_seconds > 0:
            time.sleep(settings.scenario_agent_batch_delay_seconds)

    merged = deduplicate_scenarios(llm_clean)
    merged_json = json.dumps(merged)
    if len(batches) > 1 and len(merged_json) <= settings.scenario_dedup_max_chars:
        try:
            merged = deduplicate_scenarios(_llm_dedup_batch(merged, "agent_3_final"))
        except Exception as error:
            logger.warning("agent_3 final LLM dedup failed; keeping hierarchical local result: %s", error)

    return limit_scenarios(filter_new_scenarios(deduplicate_scenarios(merged), existing_scenarios), max_scenarios)


def run_agent3_dedup(state: dict[str, Any]) -> dict[str, list[PreviewScenario]]:
    combined = [
        *state.get("agent_1_scenarios", []),
        *state.get("agent_2_scenarios", []),
    ]
    if not combined:
        return {"scenarios": []}

    options = state.get("generation_options", {})
    max_scenarios = options.get("max_scenarios") if isinstance(options, dict) else None
    existing_scenarios = state.get("existing_scenarios", [])

    try:
        return {"scenarios": _smart_dedup(combined, max_scenarios, existing_scenarios)}
    except Exception as error:
        logger.exception("agent_3 failed while smart-deduplicating %s scenarios; using local fallback: %s", len(combined), error)
        return {"scenarios": limit_scenarios(filter_new_scenarios(deduplicate_scenarios(combined), existing_scenarios), max_scenarios)}
